import { useState, useRef, useCallback } from 'react'
import { parseSemanticComment, type SemanticReview } from '../lib/parser'

interface Props {
  onLoad: (review: SemanticReview) => void
}

export default function FileInput({ onLoad }: Props) {
  const [dragging, setDragging] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileRef = useRef<HTMLInputElement>(null)

  function parse(text: string) {
    const review = parseSemanticComment(text)
    if (!review) {
      setError('Could not parse a semantic review. Expected a .json file or a .md file generated by /create-semantic-review.')
      return
    }
    setError(null)
    onLoad(review)
  }

  function handleFile(file: File) {
    const reader = new FileReader()
    reader.onload = (e) => parse(e.target?.result as string)
    reader.readAsText(file)
  }

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setDragging(false)
    const file = e.dataTransfer.files[0]
    if (file) handleFile(file)
  }, [])

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setDragging(true)
  }, [])

  const handleDragLeave = useCallback(() => setDragging(false), [])

  async function handlePaste() {
    setError(null)
    try {
      const text = await navigator.clipboard.readText()
      if (!text.trim()) {
        setError('Clipboard is empty. Copy the JSON or .md file contents first.')
        return
      }
      parse(text)
    } catch {
      setError('Could not read clipboard. Use the file picker instead, or paste into the text area below.')
    }
  }

  return (
    <div
      style={{
        minHeight: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        background: '#0d1117',
      }}
    >
      <div style={{ maxWidth: 440, width: '100%' }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>🔍</div>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: '#e6edf3', marginBottom: 8 }}>
            Semantic PR Zoom
          </h1>
          <p style={{ color: '#8b949e', fontSize: 14, lineHeight: 1.5 }}>
            Drop or paste a{' '}
            <code style={{ background: '#21262d', padding: '1px 5px', borderRadius: 4 }}>.json</code>
            {' '}or{' '}
            <code style={{ background: '#21262d', padding: '1px 5px', borderRadius: 4 }}>.md</code>
            {' '}file generated by{' '}
            <code style={{ background: '#21262d', padding: '1px 5px', borderRadius: 4 }}>/create-semantic-review</code>
          </p>
        </div>

        {/* Drop zone */}
        <div
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onClick={() => fileRef.current?.click()}
          style={{
            border: `2px dashed ${dragging ? '#58a6ff' : '#30363d'}`,
            borderRadius: 10,
            padding: '32px 24px',
            textAlign: 'center',
            cursor: 'pointer',
            background: dragging ? 'rgba(88,166,255,0.05)' : '#161b22',
            transition: 'border-color 0.15s, background 0.15s',
            marginBottom: 16,
          }}
        >
          <div style={{ fontSize: 32, marginBottom: 10 }}>📄</div>
          <p style={{ color: '#e6edf3', fontWeight: 600, fontSize: 15, marginBottom: 6 }}>
            {dragging ? 'Drop to load' : 'Drop .json or .md file here'}
          </p>
          <p style={{ color: '#8b949e', fontSize: 13 }}>or click to pick a file</p>
          <input
            ref={fileRef}
            type="file"
            accept=".json,.md,.txt"
            style={{ display: 'none' }}
            onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f) }}
          />
        </div>

        {/* Paste button */}
        <button
          onClick={handlePaste}
          style={{
            width: '100%',
            background: '#21262d',
            border: '1px solid #30363d',
            borderRadius: 8,
            padding: '12px',
            color: '#e6edf3',
            fontSize: 14,
            fontWeight: 500,
            cursor: 'pointer',
            minHeight: 44,
            marginBottom: 16,
          }}
        >
          📋 Paste from clipboard
        </button>

        {error && (
          <div
            style={{
              background: '#1c1414',
              border: '1px solid #f85149',
              borderRadius: 8,
              padding: '12px 16px',
              color: '#f85149',
              fontSize: 13,
              lineHeight: 1.5,
            }}
          >
            {error}
          </div>
        )}

        <p style={{ color: '#8b949e', fontSize: 12, marginTop: 24, textAlign: 'center', lineHeight: 1.6 }}>
          Generate a review file in your project with Claude Code:
          <br />
          <code style={{ background: '#21262d', padding: '2px 6px', borderRadius: 4, fontSize: 12 }}>
            /create-semantic-review 42
          </code>
        </p>
      </div>
    </div>
  )
}
